### ISSUE TITLE
Relative path support

### ISSUE THREAD

**Issue by chrisblossom** [sindresorhus/is-path-inside#11]
Would you accept a PR that throws an error for relative paths? Currently a relative path will be resolved at `process.cwd()` which could be surprising. I think you should explicitly resolve the path prior to calling this library.

**Comment by sindresorhus** [comment]
Resolving relative paths with `process.cwd()` is the convention. All the `path` and `fs` methods do that too. I’m not interested in throwing, but I guess we could make it clear in the readme.
