### ISSUE TITLE
Change description

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [sindresorhus/is-path-inside#3]
It is not very clear at first the difference between `is-path-inside` and `path-is-inside`. I would suggest to make it clear in the module description:

Tests whether one path is inside another path **excluding itself**.

**Comment by FagnerMartinsBrack** [comment]
X-Ref https://github.com/domenic/path-is-inside/issues/3

**Comment by sindresorhus** [comment]
A path cannot be inside itself. The original module IMHO has the wrong behavior, hence why I made this. Happy to receive a pull request that adds a clarification in the readme, but the current description is correct.

**Comment by FagnerMartinsBrack** [comment]
@sindresorhus 

> A path cannot be inside itself.

Even if the original module is wrong, what is the problem in helping to distinguish one module from another with 2 words just explaining what it does differently? It's not like the behavior of this module is going to change.

Can I ask to reconsider?

**Comment by sindresorhus** [comment]
You have two modules:
1. Check if a path is inside another path excluding itself.
2. Check if a path is inside another path.

It's still not clear the first one has different behavior than the second, as the "excluding itself" part is already implied in the main text for both.

## 

I'm not trying to be difficult. I just don't see this helping a bit.

**Comment by FagnerMartinsBrack** [comment]
It helps if both modules are:
1. Check if a path is inside another path excluding itself.
2. Check if a path is inside another path including itself.

A path inside another path can include itself as an implicit feature or not, it depends on the interpretation of one that is reading the description. An evidence that this is subjective is that somebody wrote a module assuming one or the other behavior in the first place.

The benefit in this situation is to clarify the abstraction in order to prevent subjective interpretations or having to inspect the source code for an essential information.
